// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: registry.proto

package common

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceRegistryService_Register_FullMethodName       = "/common.ServiceRegistryService/Register"
	ServiceRegistryService_Unregister_FullMethodName     = "/common.ServiceRegistryService/Unregister"
	ServiceRegistryService_Heartbeat_FullMethodName      = "/common.ServiceRegistryService/Heartbeat"
	ServiceRegistryService_GetNode_FullMethodName        = "/common.ServiceRegistryService/GetNode"
	ServiceRegistryService_GetAllNodes_FullMethodName    = "/common.ServiceRegistryService/GetAllNodes"
	ServiceRegistryService_GetWorkerNodes_FullMethodName = "/common.ServiceRegistryService/GetWorkerNodes"
)

// ServiceRegistryServiceClient is the client API for ServiceRegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ServiceRegistryService defines the service for node registration and discovery
type ServiceRegistryServiceClient interface {
	// Register registers a node with the registry
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Unregister removes a node from the registry
	Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error)
	// Heartbeat updates the heartbeat timestamp for a node
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// GetNode retrieves a node by its ID
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	// GetAllNodes returns all nodes in the registry
	GetAllNodes(ctx context.Context, in *GetAllNodesRequest, opts ...grpc.CallOption) (*GetAllNodesResponse, error)
	// GetWorkerNodes returns all worker nodes in the registry
	GetWorkerNodes(ctx context.Context, in *GetWorkerNodesRequest, opts ...grpc.CallOption) (*GetWorkerNodesResponse, error)
}

type serviceRegistryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceRegistryServiceClient(cc grpc.ClientConnInterface) ServiceRegistryServiceClient {
	return &serviceRegistryServiceClient{cc}
}

func (c *serviceRegistryServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, ServiceRegistryService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryServiceClient) Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterResponse)
	err := c.cc.Invoke(ctx, ServiceRegistryService_Unregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ServiceRegistryService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, ServiceRegistryService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryServiceClient) GetAllNodes(ctx context.Context, in *GetAllNodesRequest, opts ...grpc.CallOption) (*GetAllNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllNodesResponse)
	err := c.cc.Invoke(ctx, ServiceRegistryService_GetAllNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryServiceClient) GetWorkerNodes(ctx context.Context, in *GetWorkerNodesRequest, opts ...grpc.CallOption) (*GetWorkerNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkerNodesResponse)
	err := c.cc.Invoke(ctx, ServiceRegistryService_GetWorkerNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceRegistryServiceServer is the server API for ServiceRegistryService service.
// All implementations must embed UnimplementedServiceRegistryServiceServer
// for forward compatibility.
//
// ServiceRegistryService defines the service for node registration and discovery
type ServiceRegistryServiceServer interface {
	// Register registers a node with the registry
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Unregister removes a node from the registry
	Unregister(context.Context, *UnregisterRequest) (*UnregisterResponse, error)
	// Heartbeat updates the heartbeat timestamp for a node
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// GetNode retrieves a node by its ID
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	// GetAllNodes returns all nodes in the registry
	GetAllNodes(context.Context, *GetAllNodesRequest) (*GetAllNodesResponse, error)
	// GetWorkerNodes returns all worker nodes in the registry
	GetWorkerNodes(context.Context, *GetWorkerNodesRequest) (*GetWorkerNodesResponse, error)
	mustEmbedUnimplementedServiceRegistryServiceServer()
}

// UnimplementedServiceRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceRegistryServiceServer struct{}

func (UnimplementedServiceRegistryServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedServiceRegistryServiceServer) Unregister(context.Context, *UnregisterRequest) (*UnregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unregister not implemented")
}
func (UnimplementedServiceRegistryServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedServiceRegistryServiceServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedServiceRegistryServiceServer) GetAllNodes(context.Context, *GetAllNodesRequest) (*GetAllNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllNodes not implemented")
}
func (UnimplementedServiceRegistryServiceServer) GetWorkerNodes(context.Context, *GetWorkerNodesRequest) (*GetWorkerNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkerNodes not implemented")
}
func (UnimplementedServiceRegistryServiceServer) mustEmbedUnimplementedServiceRegistryServiceServer() {
}
func (UnimplementedServiceRegistryServiceServer) testEmbeddedByValue() {}

// UnsafeServiceRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceRegistryServiceServer will
// result in compilation errors.
type UnsafeServiceRegistryServiceServer interface {
	mustEmbedUnimplementedServiceRegistryServiceServer()
}

func RegisterServiceRegistryServiceServer(s grpc.ServiceRegistrar, srv ServiceRegistryServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceRegistryService_ServiceDesc, srv)
}

func _ServiceRegistryService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistryService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistryService_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServiceServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistryService_Unregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServiceServer).Unregister(ctx, req.(*UnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistryService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistryService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistryService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistryService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistryService_GetAllNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServiceServer).GetAllNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistryService_GetAllNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServiceServer).GetAllNodes(ctx, req.(*GetAllNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistryService_GetWorkerNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkerNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServiceServer).GetWorkerNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistryService_GetWorkerNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServiceServer).GetWorkerNodes(ctx, req.(*GetWorkerNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceRegistryService_ServiceDesc is the grpc.ServiceDesc for ServiceRegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceRegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common.ServiceRegistryService",
	HandlerType: (*ServiceRegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ServiceRegistryService_Register_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _ServiceRegistryService_Unregister_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ServiceRegistryService_Heartbeat_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _ServiceRegistryService_GetNode_Handler,
		},
		{
			MethodName: "GetAllNodes",
			Handler:    _ServiceRegistryService_GetAllNodes_Handler,
		},
		{
			MethodName: "GetWorkerNodes",
			Handler:    _ServiceRegistryService_GetWorkerNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry.proto",
}
